# Generated by Django 5.2.8 on 2026-03-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeminiImage',
        ),
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
