# Generated by Django 5.2.8 on 2026-03-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
